resource_group_name = "fh-smdo-project"
container_env_name  = "mqtt-env"
container_app_name  = "mqtt-client"
broker_url          = "iothub.magenta.at"
image_name          = "ghcr.io/ahmaad-dev/my-mqtt-project:mqttclient-v1"
