resource_group_name = "fh-smdo-project"
image_name          = "ghcr.io/ahmaad-dev/my-mqtt-project:mqttclient-v1"
broker_url          = "demo.thingsboard.io"
access_token        = "r4kj6nnxch43dc4b1amb"
ca_file             = "ca-root.pem"
