name: Deploy MQTT Client to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Login via OIDC using Managed Identity'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan \
            -var="access_token=${{ secrets.ACCESS_TOKEN }}"
        working-directory: ./terraform

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/ahmaad-dev/my-mqtt-project:mqttclient-v1 ./projectroot

      - name: Push Docker image
        run: docker push ghcr.io/ahmaad-dev/my-mqtt-project:mqttclient-v1

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform
